/* Money Graph, screen language.
   Russian by default, Kazakh and English on the switch in the top bar. English is the key,
   so a string missing from a dictionary falls back to itself rather than to a blank.
   Only what the screen itself says is translated here. Evidence strings, hypotheses and
   reasons are generated by the pipeline in English and shown as they are. */

let stored = null;
try { stored = localStorage.getItem("mg.lang"); } catch {}
export const LANG = ["ru", "kk", "en"].includes(stored) ? stored : "ru";
export const LOCALE = { ru: "ru-RU", kk: "kk-KZ", en: "en-GB" }[LANG];
export function setLang(l) { try { localStorage.setItem("mg.lang", l); } catch {} location.reload(); }

/* The theme is remembered the same way, and applied before anything draws. */
try { if (localStorage.getItem("mg.theme") === "dark") document.documentElement.dataset.theme = "dark"; } catch {}

const RU = {
  "find an account by id": "найти счёт по идентификатору",
  "Case file": "Дело", "outbound crawl, 4 hops · 1–31 July 2026": "исходящий обход, 4 шага · 1–31 июля 2026",
  "Paper": "Бумага", "Dark": "Тёмная",
  "The run output could not be read. This screen expects out/graph.json beside it, served over HTTP rather than opened from disk. Start it with: python3 run.py --serve":
    "Не удалось прочитать результат расчёта. Экран ожидает файл out/graph.json рядом с собой, отданный по HTTP, а не открытый с диска. Запустите: python3 run.py --serve",
  "Start": "Начало", "the case in one screen": "дело на одном экране",
  "Who to review first": "Кого проверить первым", "ranked, with reasons": "ранжировано, с обоснованием",
  "One account": "Один счёт", "its money, its role, its neighbours": "его деньги, роль и окружение",
  "Structures": "Структуры", "funnels, chains, loops, fan-outs": "воронки, цепочки, возвраты, веера",
  "Replay the month": "Прокрутить месяц", "July, day by day": "июль, день за днём",
  "Amount echoes": "Эхо сумм", "same sum in, same sum out": "та же сумма вошла и вышла",
  "Where the data runs out": "Где заканчиваются данные", "and what to ask for next": "и что запросить дальше",
  "Every figure is a measurement from the July extract. Every reading of it is a hypothesis to test, not a finding of guilt.":
    "Каждая цифра — измерение по июльской выгрузке. Каждое её прочтение — гипотеза для проверки, а не вывод о виновности.",
  "known clients": "известные клиенты", "hop {n}": "шаг {n}",
  "2 hops in": "2 шага до", "paid it": "платили ему", "this one": "этот счёт", "paid by it": "получали от него", "2 hops out": "2 шага после",
  "paid the payers": "платили плательщикам", "paid this account": "платили этому счёту", "this account": "этот счёт",
  "were paid by it": "получали от него", "were paid next": "получали следом",
  "breaking point": "точка разрыва",
  "An account law enforcement already named": "Счёт, уже названный правоохранительными органами", "known client": "известный клиент",
  "All {n} accounts": "Все {n} счетов",
  "left to right is distance from the known clients · the selection and its transfers are lit": "слева направо — расстояние от известных клиентов · выбранный счёт и его переводы подсвечены",
  "Around {id}": "Вокруг {id}", "paid by {a}, paid {b}": "платили {a}, получали {b}",
  "{n} of them also paid it, drawn once on the left with arrows both ways": "{n} из них также платили ему; показаны один раз слева со стрелками в обе стороны",
  "{n} accounts with the smallest transfers are not drawn so the rest stay readable. Whole network shows everything.":
    "{n} счетов с наименьшими переводами не показаны, чтобы остальное оставалось читаемым. «Вся сеть» показывает всё.",
  "This account": "Этот счёт",
  "Received <b>{in}</b> from {a} and sent <b>{out}</b> to {b} in July.": "В июле получил <b>{in}</b> от {a} и отправил <b>{out}</b> на {b}.",
  "account": "счёт", "accounts": "счетов",
  "Assessed as": "Оценка", "rule confidence": "уверенность правила", "The rule fired on:": "Правило сработало на:",
  "This account sits at hop {n} with nothing recorded going out. The crawl stopped here, so whether the money stopped here is not something this data can say.":
    "Счёт находится на шаге {n}, исходящих переводов не зафиксировано. Обход остановился здесь, поэтому остановились ли здесь деньги — по этим данным сказать нельзя.",
  "Investigation priority": "Приоритет проверки", "of": "из", "not in the top {n}": "не входит в топ-{n}", "0 to 1, higher first": "от 0 до 1, выше — раньше",
  "Position": "Положение", "hops from a known client": "шагов от известного клиента", "known": "известный", "group": "группа",
  "What we know of it": "Что о нём известно", "confidence": "уверенность",
  "fully_observed": "наблюдается полностью", "outbound_only": "только исходящие", "inbound_only": "только входящие",
  "truncated_at_depth": "обрезан глубиной обхода", "isolated": "изолирован", "partial": "частично",
  "Structures it belongs to": "Структуры, в которые он входит", "and {n} more": "и ещё {n}",
  "None. It is not part of any funnel, chain, loop, fan-out or bridge.": "Ни одной. Не входит ни в воронку, ни в цепочку, ни в возврат, ни в веер, ни в мост.",
  "No account with the id {id} in this extract.": "Счёта с идентификатором {id} в этой выгрузке нет.",
  "Pick an account from any list, or type its id above. The map shows the money around it: who paid it on the left, who it paid on the right. Every arrow points the way the money moved.":
    "Выберите счёт в любом списке или введите его идентификатор выше. Карта показывает деньги вокруг него: слева — кто ему платил, справа — кому платил он. Каждая стрелка направлена по ходу денег.",
  "Around this account": "Вокруг счёта", "Whole network": "Вся сеть",
  "A ranked account is a name, and an investigator cannot act on a name. These are groups of accounts that only make sense read together, ranked by what an investigator can act on. Each carries its <b>breaking point</b>: the one account whose removal breaks most of it.":
    "Счёт в рейтинге — это просто имя, а по имени действовать нельзя. Здесь — группы счетов, которые имеют смысл только вместе, ранжированные по тому, с чем может работать проверяющий. У каждой есть <b>точка разрыва</b>: тот единственный счёт, удаление которого разрушает большую часть структуры.",
  "across": "на", "hop": "шаге", "hops": "шагах", "through it": "через неё",
  "{n} more are in out/formations.csv.": "Ещё {n} — в out/formations.csv.",
  "accounts cut off": "счетов отрезано", "KZT stopped": "KZT остановлено",
  "This structure": "Эта структура", "of them known": "из них известных", "moving through it": "проходит через неё",
  "Breaking point": "Точка разрыва",
  "Remove this one account and {n} {unit}. Found by {method}. Marked in amber on the map.": "Уберите этот один счёт — и {n} {unit}. Метод: {method}. На карте выделен янтарным.",
  "Not identified for this structure.": "Для этой структуры не определена.",
  "Hypothesis to test": "Гипотеза для проверки", "Arithmetic behind it:": "Арифметика:", "Members": "Участники",
  "The {k} accounts the evidence puts first, out of {n}. Ranked on the rules that fired and the numbers they fired on, not on how central an account is. <b>Click a row</b> to open the account.":
    "{k} счетов из {n}, которые доказательства ставят первыми. Ранжированы по сработавшим правилам и цифрам, на которых они сработали, а не по центральности счёта. <b>Нажмите на строку</b>, чтобы открыть счёт.",
  "assessed as": "оценка", "priority": "приоритет", "the reason, in the rule's own numbers": "причина, в цифрах самого правила",
  "accounts at hop {n} with nothing going out. The crawl stopped, not the money.": "счетов на шаге {n} без исходящих переводов. Остановился обход, а не деньги.",
  "dead ends the crawl did follow to their end": "тупиков, которые обход проследил до конца",
  "of the {n} known clients appear in no transfer at all": "из {n} известных клиентов не встречаются ни в одном переводе",
  "known clients sent nothing in the window": "известных клиентов ничего не отправили за период",
  "of accounts sit at the crawl boundary": "счетов находятся на границе обхода",
  "of turnover ends at the crawl boundary": "оборота заканчивается на границе обхода",
  "isolated accounts, no transfer either way": "изолированных счетов, ни одного перевода в обе стороны",
  "The crawl followed money <b>outwards</b> from the {n} known clients for four hops. Money arriving into them was never followed, so anyone directing them from above is outside this extract by construction. These are the measured limits, and what to ask for next.":
    "Обход шёл <b>от</b> {n} известных клиентов наружу на четыре шага. Деньги, приходившие к ним, не прослеживались, поэтому тот, кто управляет ими сверху, по построению остаётся за пределами выгрузки. Здесь — измеренные границы и что запросить дальше.",
  "What to ask the data owner for next": "Что запросить у владельца данных дальше", "Ranked by what each request would resolve.": "По тому, что разрешит каждый запрос.",
  "accounts resolved": "счетов прояснится", "lit up": "станет видно", "Not generated in this run.": "В этом расчёте не сформировано.",
  "Where a plain centrality ranking would mislead": "Где простой рейтинг по центральности вводит в заблуждение",
  "Centrality promotes accounts that flow passes through. It cannot tell an account collecting from many payers apart from a business paying many suppliers. These accounts moved most between the two rankings.":
    "Центральность поднимает счета, через которые проходит поток. Она не отличает счёт, собирающий деньги со многих плательщиков, от бизнеса, платящего многим поставщикам. Эти счета сильнее всего сдвинулись между двумя рейтингами.",
  "by centrality": "по центральности", "by evidence": "по доказательствам", "the numbers": "цифры",
  "If the top-ranked accounts were removed": "Если убрать счета из верха рейтинга",
  "A ranking is only worth having if acting on it changes the network.": "Рейтинг чего-то стоит, только если действие по нему меняет сеть.",
  "removed": "убрано", "largest group left": "крупнейшая оставшаяся группа", "separate pieces": "отдельных частей", "still reachable from known clients": "по-прежнему достижимы от известных клиентов",
  "This section could not start:": "Раздел не запустился:", "This section's module is not present in this build.": "Модуль этого раздела отсутствует в сборке.",
  "The case in one screen": "Дело на одном экране",
  "Law enforcement named <b>{n} accounts</b> at the bottom of a chain. A crawl followed their outbound transfers for four hops through July 2026. This tool reads what the crawl brought back and answers one question: <b>which of these accounts should an analyst look at first, and why.</b>":
    "Правоохранительные органы назвали <b>{n} счетов</b> в нижнем звене цепочки. Обход проследил их исходящие переводы на четыре шага за июль 2026 года. Этот инструмент читает то, что принёс обход, и отвечает на один вопрос: <b>какие из этих счетов аналитику стоит посмотреть первыми и почему.</b>",
  "known clients, where the crawl began": "известных клиентов, откуда начался обход", "accounts reached in four hops": "счетов достигнуто за четыре шага",
  "transfer relationships": "связей по переводам", "accounts to review first": "счетов проверить первыми",
  "structures that only make sense read together": "структур, которые имеют смысл только вместе",
  "accounts not judged, because the data does not support a judgement": "счетов без оценки: данных для неё недостаточно",
  "Start with these accounts": "Начните с этих счетов", "RANK": "МЕСТО", "PRIORITY": "ПРИОРИТЕТ", "All {n} ranked accounts": "Все {n} счетов рейтинга",
  "Start with these structures": "Начните с этих структур", "All {n} structures": "Все {n} структур", "Also in this file": "Также в этом деле",
  "the busiest day: {kzt} in {n} transfers.": "самый активный день: {kzt} в {n} переводах.",
  "amount echoes: the same sum in and out within a day, or the same sum to several receivers.": "эхо сумм: та же сумма вошла и вышла в пределах дня либо ушла нескольким получателям.",
  "See them": "Посмотреть", "accounts where the crawl stopped rather than the money.": "счетов, где остановился обход, а не деньги.",
  "July 2026, one day at a time, on the same hop layout: known clients on the left, four hops to the right. Watch which days carry the bursts and how far the money travels in a day.":
    "Июль 2026 года по одному дню на той же схеме шагов: известные клиенты слева, четыре шага вправо. Видно, на какие дни приходятся всплески и как далеко деньги уходят за день.",
  "An exact sum arrives at an account and leaves again as the same sum, or split into parts, within a day. Or one account sends the identical amount to several receivers on the same day. Each is a hypothesis for an analyst to check against what the transfers were said to be for.":
    "Точная сумма приходит на счёт и в пределах дня уходит той же суммой или частями. Либо один счёт в один день отправляет одинаковую сумму нескольким получателям. Каждое — гипотеза, которую аналитик сверяет с заявленным назначением переводов.",
};

const KK = {
  "find an account by id": "шотты идентификаторы бойынша табу",
  "Case file": "Іс", "outbound crawl, 4 hops · 1–31 July 2026": "шығыс аударымдар бойынша обход, 4 қадам · 2026 ж. 1–31 шілде",
  "Paper": "Қағаз", "Dark": "Қараңғы",
  "The run output could not be read. This screen expects out/graph.json beside it, served over HTTP rather than opened from disk. Start it with: python3 run.py --serve":
    "Есептеу нәтижесін оқу мүмкін болмады. Экран қасында HTTP арқылы берілген out/graph.json файлын күтеді, дискіден ашылғанын емес. Іске қосыңыз: python3 run.py --serve",
  "Start": "Басы", "the case in one screen": "іс бір экранда",
  "Who to review first": "Кімді бірінші тексеру керек", "ranked, with reasons": "негіздемесімен ранжирленген",
  "One account": "Бір шот", "its money, its role, its neighbours": "оның ақшасы, рөлі және айналасы",
  "Structures": "Құрылымдар", "funnels, chains, loops, fan-outs": "воронкалар, тізбектер, қайтарымдар, желпуіштер",
  "Replay the month": "Айды қайта көру", "July, day by day": "шілде, күн сайын",
  "Amount echoes": "Сома жаңғырығы", "same sum in, same sum out": "сол сома кірді, сол сома шықты",
  "Where the data runs out": "Деректер қайда таусылады", "and what to ask for next": "және әрі қарай не сұрау керек",
  "Every figure is a measurement from the July extract. Every reading of it is a hypothesis to test, not a finding of guilt.":
    "Әр сан — шілде айындағы деректер бойынша өлшем. Оның әр түсіндірмесі — тексеруге арналған гипотеза, кінә туралы қорытынды емес.",
  "known clients": "белгілі клиенттер", "hop {n}": "{n}-қадам",
  "2 hops in": "2 қадам бұрын", "paid it": "оған төледі", "this one": "осы шот", "paid by it": "одан алды", "2 hops out": "2 қадам кейін",
  "paid the payers": "төлеушілерге төледі", "paid this account": "осы шотқа төледі", "this account": "осы шот",
  "were paid by it": "одан алды", "were paid next": "келесі алды",
  "breaking point": "үзілу нүктесі",
  "An account law enforcement already named": "Құқық қорғау органдары атаған шот", "known client": "белгілі клиент",
  "All {n} accounts": "Барлық {n} шот",
  "left to right is distance from the known clients · the selection and its transfers are lit": "солдан оңға — белгілі клиенттерден қашықтық · таңдалған шот пен оның аударымдары бөлектелген",
  "Around {id}": "{id} айналасы", "paid by {a}, paid {b}": "{a} төледі, {b} алды",
  "{n} of them also paid it, drawn once on the left with arrows both ways": "олардың {n}-і оған да төледі; сол жақта бір рет, екі бағытты көрсеткімен көрсетілген",
  "{n} accounts with the smallest transfers are not drawn so the rest stay readable. Whole network shows everything.":
    "Ең кіші аударымы бар {n} шот оқылымды сақтау үшін көрсетілмеген. «Бүкіл желі» бәрін көрсетеді.",
  "This account": "Осы шот",
  "Received <b>{in}</b> from {a} and sent <b>{out}</b> to {b} in July.": "Шілдеде {a} шоттан <b>{in}</b> алды және {b} шотқа <b>{out}</b> жіберді.",
  "account": "шот", "accounts": "шот",
  "Assessed as": "Бағасы", "rule confidence": "ереже сенімділігі", "The rule fired on:": "Ереже мынаған сүйенді:",
  "This account sits at hop {n} with nothing recorded going out. The crawl stopped here, so whether the money stopped here is not something this data can say.":
    "Шот {n}-қадамда тұр, шығыс аударым тіркелмеген. Обход осы жерде тоқтады, сондықтан ақша осында тоқтады ма — бұл деректерден айту мүмкін емес.",
  "Investigation priority": "Тексеру басымдығы", "of": "/", "not in the top {n}": "топ-{n} ішінде емес", "0 to 1, higher first": "0-ден 1-ге дейін, жоғарысы бірінші",
  "Position": "Орны", "hops from a known client": "белгілі клиенттен қадам саны", "known": "белгілі", "group": "топ",
  "What we know of it": "Ол туралы не білеміз", "confidence": "сенімділік",
  "fully_observed": "толық бақыланады", "outbound_only": "тек шығыс", "inbound_only": "тек кіріс",
  "truncated_at_depth": "обход тереңдігімен шектелген", "isolated": "оқшауланған", "partial": "ішінара",
  "Structures it belongs to": "Кіретін құрылымдары", "and {n} more": "және тағы {n}",
  "None. It is not part of any funnel, chain, loop, fan-out or bridge.": "Жоқ. Ешбір воронкаға, тізбекке, қайтарымға, желпуішке немесе көпірге кірмейді.",
  "No account with the id {id} in this extract.": "Бұл деректерде {id} идентификаторлы шот жоқ.",
  "Pick an account from any list, or type its id above. The map shows the money around it: who paid it on the left, who it paid on the right. Every arrow points the way the money moved.":
    "Кез келген тізімнен шотты таңдаңыз немесе жоғарыда идентификаторын енгізіңіз. Карта оның айналасындағы ақшаны көрсетеді: сол жақта — оған кім төледі, оң жақта — ол кімге төледі. Әр көрсеткі ақша бағытын көрсетеді.",
  "Around this account": "Шот айналасы", "Whole network": "Бүкіл желі",
  "A ranked account is a name, and an investigator cannot act on a name. These are groups of accounts that only make sense read together, ranked by what an investigator can act on. Each carries its <b>breaking point</b>: the one account whose removal breaks most of it.":
    "Рейтингтегі шот — тек атау, ал атау бойынша әрекет ету мүмкін емес. Мұнда тек бірге қарағанда мағынасы бар шоттар топтары, тексерушінің әрекет ете алатынына қарай ранжирленген. Әрқайсысының <b>үзілу нүктесі</b> бар: алып тастағанда құрылымның көп бөлігін бұзатын жалғыз шот.",
  "across": "—", "hop": "қадам", "hops": "қадам", "through it": "ол арқылы",
  "{n} more are in out/formations.csv.": "Тағы {n} — out/formations.csv ішінде.",
  "accounts cut off": "шот ажырайды", "KZT stopped": "KZT тоқтайды",
  "This structure": "Осы құрылым", "of them known": "белгілі", "moving through it": "ол арқылы өтеді",
  "Breaking point": "Үзілу нүктесі",
  "Remove this one account and {n} {unit}. Found by {method}. Marked in amber on the map.": "Осы бір шотты алып тастаңыз — {n} {unit}. Әдіс: {method}. Картада янтарь түспен белгіленген.",
  "Not identified for this structure.": "Бұл құрылым үшін анықталмаған.",
  "Hypothesis to test": "Тексеруге арналған гипотеза", "Arithmetic behind it:": "Есебі:", "Members": "Қатысушылар",
  "The {k} accounts the evidence puts first, out of {n}. Ranked on the rules that fired and the numbers they fired on, not on how central an account is. <b>Click a row</b> to open the account.":
    "{n} шоттың ішінен дәлелдер бірінші қойған {k} шот. Шоттың орталықтығы бойынша емес, іске қосылған ережелер мен олар сүйенген сандар бойынша ранжирленген. Шотты ашу үшін <b>жолды басыңыз</b>.",
  "assessed as": "бағасы", "priority": "басымдық", "the reason, in the rule's own numbers": "себебі, ереженің өз сандарымен",
  "accounts at hop {n} with nothing going out. The crawl stopped, not the money.": "{n}-қадамдағы шығыс аударымы жоқ шот. Ақша емес, обход тоқтады.",
  "dead ends the crawl did follow to their end": "обход соңына дейін бақылаған тұйықтар",
  "of the {n} known clients appear in no transfer at all": "{n} белгілі клиенттің ішінен ешбір аударымда кездеспейді",
  "known clients sent nothing in the window": "белгілі клиент кезеңде ештеңе жібермеген",
  "of accounts sit at the crawl boundary": "шот обход шекарасында тұр",
  "of turnover ends at the crawl boundary": "айналым обход шекарасында аяқталады",
  "isolated accounts, no transfer either way": "оқшауланған шот, екі бағытта да аударым жоқ",
  "The crawl followed money <b>outwards</b> from the {n} known clients for four hops. Money arriving into them was never followed, so anyone directing them from above is outside this extract by construction. These are the measured limits, and what to ask for next.":
    "Обход {n} белгілі клиенттен ақшаны <b>сыртқа қарай</b> төрт қадам бақылады. Оларға келген ақша бақыланбады, сондықтан оларды жоғарыдан басқаратын адам құрылымы бойынша бұл деректерден тыс қалады. Мұнда — өлшенген шектер және әрі қарай не сұрау керек.",
  "What to ask the data owner for next": "Деректер иесінен әрі қарай не сұрау керек", "Ranked by what each request would resolve.": "Әр сұраныстың нені шешетініне қарай.",
  "accounts resolved": "шот анықталады", "lit up": "көрінеді", "Not generated in this run.": "Бұл есептеуде қалыптаспаған.",
  "Where a plain centrality ranking would mislead": "Қарапайым орталықтық рейтингі қайда адастырады",
  "Centrality promotes accounts that flow passes through. It cannot tell an account collecting from many payers apart from a business paying many suppliers. These accounts moved most between the two rankings.":
    "Орталықтық ағын өтетін шоттарды жоғары көтереді. Ол көп төлеушіден ақша жинайтын шотты көп жеткізушіге төлейтін бизнестен ажырата алмайды. Бұл шоттар екі рейтинг арасында ең көп ауысты.",
  "by centrality": "орталықтық бойынша", "by evidence": "дәлелдер бойынша", "the numbers": "сандар",
  "If the top-ranked accounts were removed": "Рейтингтің жоғарғы шоттарын алып тастаса",
  "A ranking is only worth having if acting on it changes the network.": "Рейтингтің құны — ол бойынша әрекет желіні өзгерткенде ғана.",
  "removed": "алынды", "largest group left": "қалған ең үлкен топ", "separate pieces": "бөлек бөлік", "still reachable from known clients": "белгілі клиенттерден әлі де қолжетімді",
  "This section could not start:": "Бөлім іске қосылмады:", "This section's module is not present in this build.": "Бұл бөлімнің модулі жинақта жоқ.",
  "The case in one screen": "Іс бір экранда",
  "Law enforcement named <b>{n} accounts</b> at the bottom of a chain. A crawl followed their outbound transfers for four hops through July 2026. This tool reads what the crawl brought back and answers one question: <b>which of these accounts should an analyst look at first, and why.</b>":
    "Құқық қорғау органдары тізбектің төменгі буынындағы <b>{n} шотты</b> атады. Обход олардың шығыс аударымдарын 2026 жылғы шілдеде төрт қадам бойы бақылады. Бұл құрал обход әкелгенді оқып, бір сұраққа жауап береді: <b>талдаушы осы шоттардың қайсысын бірінші қарауы керек және неге.</b>",
  "known clients, where the crawl began": "белгілі клиент, обход осыдан басталды", "accounts reached in four hops": "шотқа төрт қадамда жетті",
  "transfer relationships": "аударым байланысы", "accounts to review first": "шотты бірінші тексеру керек",
  "structures that only make sense read together": "тек бірге қарағанда мағынасы бар құрылым",
  "accounts not judged, because the data does not support a judgement": "бағаланбаған шот: деректер жеткіліксіз",
  "Start with these accounts": "Осы шоттардан бастаңыз", "RANK": "ОРЫН", "PRIORITY": "БАСЫМДЫҚ", "All {n} ranked accounts": "Рейтингтегі барлық {n} шот",
  "Start with these structures": "Осы құрылымдардан бастаңыз", "All {n} structures": "Барлық {n} құрылым", "Also in this file": "Бұл істе тағы",
  "the busiest day: {kzt} in {n} transfers.": "ең белсенді күн: {n} аударымда {kzt}.",
  "amount echoes: the same sum in and out within a day, or the same sum to several receivers.": "сома жаңғырығы: сол сома бір күн ішінде кіріп-шықты немесе бірнеше алушыға кетті.",
  "See them": "Қарау", "accounts where the crawl stopped rather than the money.": "ақша емес, обход тоқтаған шот.",
  "July 2026, one day at a time, on the same hop layout: known clients on the left, four hops to the right. Watch which days carry the bursts and how far the money travels in a day.":
    "2026 жылғы шілде, сол қадам сызбасында күн сайын: белгілі клиенттер сол жақта, төрт қадам оң жаққа. Қай күндері серпіліс болғаны және ақшаның бір күнде қаншалықты алыс кететіні көрінеді.",
  "An exact sum arrives at an account and leaves again as the same sum, or split into parts, within a day. Or one account sends the identical amount to several receivers on the same day. Each is a hypothesis for an analyst to check against what the transfers were said to be for.":
    "Нақты сома шотқа келіп, бір күн ішінде сол сомамен немесе бөліктерге бөлініп қайта шығады. Немесе бір шот бір күнде бірдей соманы бірнеше алушыға жібереді. Әрқайсысы — талдаушы аударымдардың мәлімделген мақсатымен салыстырып тексеретін гипотеза.",
};

const DICT = { ru: RU, kk: KK, en: {} };
export const t = k => DICT[LANG][k] ?? k;

/* Role names and their plain definitions. The thresholds are the ones in src/moneygraph/roles.py. */
const ROLE_NAMES = {
  ru: { consolidator: "консолидатор", coordinator: "координатор", transit: "транзит", distributor: "распределитель", terminal: "конечный получатель",
        peripheral: "периферия", abstained_boundary: "без оценки: граница обхода", abstained_single_observation: "без оценки: одно наблюдение", "known client": "известный клиент" },
  kk: { consolidator: "консолидатор", coordinator: "координатор", transit: "транзит", distributor: "таратушы", terminal: "соңғы алушы",
        peripheral: "перифериялық", abstained_boundary: "бағасыз: обход шекарасы", abstained_single_observation: "бағасыз: жалғыз бақылау", "known client": "белгілі клиент" },
  en: {},
};
const ROLE_DEFS = {
  en: {
    consolidator: "Paid by 8 or more different accounts and keeps most of it, passing on less than half.",
    coordinator: "Receives from 4 or more accounts and pays 4 or more. Money moves through it in both directions.",
    transit: "Passes on roughly what it receives, between 80% and 120%.",
    distributor: "Pays out to 20 or more receivers.",
    terminal: "Money arrives and nothing leaves, and it sits before the crawl's edge, so the money appears to stay.",
    peripheral: "No rule threshold met: low activity, or a known client with only outbound transfers recorded.",
    abstained_boundary: "Sits at hop 4 with nothing going out. The crawl stopped here, so no judgement is made.",
    abstained_single_observation: "Fewer than three transfers in total. Too little to judge.",
  },
  ru: {
    consolidator: "Получает от 8 и более разных счетов и оставляет большую часть у себя, передавая дальше меньше половины.",
    coordinator: "Получает от 4 и более счетов и платит 4 и более. Деньги проходят через него в обе стороны.",
    transit: "Передаёт дальше примерно столько же, сколько получает: от 80% до 120%.",
    distributor: "Платит 20 и более получателям.",
    terminal: "Деньги приходят и не уходят, при этом счёт находится до границы обхода, поэтому деньги, по-видимому, остаются.",
    peripheral: "Ни один порог правил не достигнут: низкая активность либо известный клиент, у которого зафиксированы только исходящие переводы.",
    abstained_boundary: "Находится на шаге 4 без исходящих переводов. Обход здесь остановился, поэтому оценка не выносится.",
    abstained_single_observation: "Менее трёх переводов всего. Слишком мало для оценки.",
  },
  kk: {
    consolidator: "8 және одан көп түрлі шоттан алады және көп бөлігін өзінде қалдырады, жартысынан азын әрі қарай жібереді.",
    coordinator: "4 және одан көп шоттан алады және 4 және одан көпке төлейді. Ақша ол арқылы екі бағытта өтеді.",
    transit: "Алғанын шамамен сол көлемде әрі қарай жібереді: 80%-дан 120%-ға дейін.",
    distributor: "20 және одан көп алушыға төлейді.",
    terminal: "Ақша келеді және кетпейді, әрі шот обход шекарасына дейін тұр, сондықтан ақша қалатын сияқты.",
    peripheral: "Ешбір ереже шегіне жетпеген: белсенділік төмен немесе тек шығыс аударымы тіркелген белгілі клиент.",
    abstained_boundary: "4-қадамда тұр, шығыс аударым жоқ. Обход осы жерде тоқтады, сондықтан баға берілмейді.",
    abstained_single_observation: "Барлығы үштен аз аударым. Бағалауға тым аз.",
  },
};
const KIND_NAMES = {
  ru: { funnel: "воронка", chain: "цепочка", reciprocal_loop: "возврат", fan_out: "веер", bridge: "мост" },
  kk: { funnel: "воронка", chain: "тізбек", reciprocal_loop: "қайтарым", fan_out: "желпуіш", bridge: "көпір" },
  en: {},
};
const KIND_DEFS = {
  en: {
    funnel: "several accounts each send most of their outflow to one collection point",
    chain: "money forwarded account to account, each passing on most of what arrived",
    reciprocal_loop: "money sent and sent back, a pair or a short cycle",
    fan_out: "one account paying many receivers that send nothing on",
    bridge: "one account that part of a group depends on to reach the rest of the network",
  },
  ru: {
    funnel: "несколько счетов отправляют большую часть своих исходящих в одну точку сбора",
    chain: "деньги передаются от счёта к счёту, каждый передаёт дальше большую часть полученного",
    reciprocal_loop: "деньги отправлены и возвращены: пара или короткий цикл",
    fan_out: "один счёт платит многим получателям, которые ничего не передают дальше",
    bridge: "один счёт, через который часть группы связана с остальной сетью",
  },
  kk: {
    funnel: "бірнеше шот шығыс аударымдарының көп бөлігін бір жинау нүктесіне жібереді",
    chain: "ақша шоттан шотқа беріледі, әрқайсысы алғанының көп бөлігін әрі қарай жібереді",
    reciprocal_loop: "ақша жіберіліп, қайтарылды: жұп немесе қысқа цикл",
    fan_out: "бір шот әрі қарай ештеңе жібермейтін көп алушыға төлейді",
    bridge: "топтың бір бөлігі желінің қалған бөлігіне тек сол арқылы жететін жалғыз шот",
  },
};
export const ROLE_DEF = ROLE_DEFS[LANG];
export const KIND_DEF = KIND_DEFS[LANG];
export const roleName = r => ROLE_NAMES[LANG][r] ?? String(r ?? "").replace(/_/g, " ");
export const kindName = k => KIND_NAMES[LANG][k] ?? String(k ?? "").replace(/_/g, " ");
