/* Money Graph, screen language.
   English by default, Russian and Kazakh on the switch in the top bar. The key is the
   English string used in index.html; DICT.en carries the plain-English wording shown on
   screen, so a string missing from a dictionary falls back to its key rather than to a blank.
   Only what the screen itself says is translated here. Evidence strings, hypotheses and
   reasons are generated by the pipeline in English and shown as they are. */

let stored = null;
try { stored = localStorage.getItem("mg.lang"); } catch {}
export const LANG = ["ru", "kk", "en"].includes(stored) ? stored : "en";
export const LOCALE = { ru: "ru-RU", kk: "kk-KZ", en: "en-GB" }[LANG];
export function setLang(l) { try { localStorage.setItem("mg.lang", l); } catch {} location.reload(); }

/* The theme is remembered the same way, and applied before anything draws. */
try { if (localStorage.getItem("mg.theme") === "dark") document.documentElement.dataset.theme = "dark"; } catch {}

/* Plain-English wording for keys whose original text was not literal. A key absent here is shown as is. */
const EN = {
  "Case file": "Data set", "outbound crawl, 4 hops · 1–31 July 2026": "outgoing transfers, up to 4 hops · 1–31 July 2026",
  "Paper": "Light",
  "Start": "Overview", "the case in one screen": "figures and where to start",
  "Who to review first": "Priority accounts", "ranked, with reasons": "ranked list, reason for each rank",
  "One account": "Account", "its money, its role, its neighbours": "transfers in and out, role, priority",
  "Structures": "Linked account groups", "funnels, chains, loops, fan-outs": "groups found by the rules",
  "Replay the month": "Transfers by day", "July, day by day": "1–31 July 2026",
  "Amount echoes": "Matching amounts", "same sum in, same sum out": "same sum in and out within a day",
  "Where the data runs out": "Data limitations", "and what to ask for next": "what the data does not cover",
  "Every figure is a measurement from the July extract. Every reading of it is a hypothesis to test, not a finding of guilt.":
    "All figures are computed from the July 2026 data. Roles and rankings are hypotheses for the analyst to verify.",
  "known clients": "listed accounts",
  "2 hops in": "2 transfers before", "paid it": "paid this account", "this one": "this account", "paid by it": "paid by this account", "2 hops out": "2 transfers after",
  "paid the payers": "paid the accounts that paid it", "were paid by it": "received from it", "were paid next": "received from those",
  "breaking point": "key account",
  "An account law enforcement already named": "An account on the list received from law enforcement", "known client": "listed account",
  "left to right is distance from the known clients · the selection and its transfers are lit": "left to right: number of transfers away from a listed account · the selected account and its transfers are highlighted",
  "Around {id}": "Accounts linked to {id}", "paid by {a}, paid {b}": "received from {a}, sent to {b}",
  "{n} of them also paid it, drawn once on the left with arrows both ways": "{n} of them both sent to and received from it; shown once on the left with arrows in both directions",
  "{n} accounts with the smallest transfers are not drawn so the rest stay readable. Whole network shows everything.":
    "{n} accounts with the smallest transfers are not shown. The All accounts view shows all of them.",
  "Assessed as": "Role", "The rule fired on:": "Figures the rule used:",
  "This account sits at hop {n} with nothing recorded going out. The crawl stopped here, so whether the money stopped here is not something this data can say.":
    "This account is {n} transfers away from a listed account and has no recorded outgoing transfers. The data does not go further, so it is not possible to say whether the money stayed here.",
  "Investigation priority": "Review priority", "0 to 1, higher first": "scale 0 to 1; higher means review earlier",
  "hops from a known client": "transfers away from a listed account", "known": "listed",
  "What we know of it": "Data coverage",
  "fully_observed": "incoming and outgoing transfers recorded", "outbound_only": "outgoing transfers only", "inbound_only": "incoming transfers only",
  "truncated_at_depth": "at the 4-transfer limit of the data", "isolated": "no transfers recorded", "partial": "partly recorded",
  "Structures it belongs to": "Groups it belongs to",
  "None. It is not part of any funnel, chain, loop, fan-out or bridge.": "None. This account is not in any linked account group.",
  "No account with the id {id} in this extract.": "No account with id {id} in the data.",
  "Pick an account from any list, or type its id above. The map shows the money around it: who paid it on the left, who it paid on the right. Every arrow points the way the money moved.":
    "Choose an account from any list or type its id in the search box. The map shows accounts that sent money to it on the left and accounts it sent money to on the right. Arrows point from sender to receiver.",
  "Around this account": "Linked accounts", "Whole network": "All accounts",
  "A ranked account is a name, and an investigator cannot act on a name. These are groups of accounts that only make sense read together, ranked by what an investigator can act on. Each carries its <b>breaking point</b>: the one account whose removal breaks most of it.":
    "Groups of accounts that the rules found to be linked by their transfers, ranked by the amount transferred and by how many members depend on one account. Each group has a <b>key account</b>: the account whose removal disconnects the most members of the group.",
  "through it": "transferred within the group",
  "accounts cut off": "members are disconnected from the group", "KZT stopped": "KZT of transfers no longer pass",
  "This structure": "This group", "of them known": "on the list", "moving through it": "transferred within the group",
  "Breaking point": "Key account",
  "Remove this one account and {n} {unit}. Found by {method}. Marked in amber on the map.": "If this account is removed, {n} {unit}. Method: {method}. Shown in amber on the map.",
  "Not identified for this structure.": "Not identified for this group.",
  "Hypothesis to test": "Hypothesis to verify", "Arithmetic behind it:": "Figures behind it:",
  "The {k} accounts the evidence puts first, out of {n}. Ranked on the rules that fired and the numbers they fired on, not on how central an account is. <b>Click a row</b> to open the account.":
    "The {k} of {n} accounts with the highest priority. Priority is computed from the rules that matched and the figures they matched on, not from how many connections an account has. <b>Click a row</b> to open the account.",
  "assessed as": "role", "the reason, in the rule's own numbers": "reason: the figures the rule matched on",
  "accounts at hop {n} with nothing going out. The crawl stopped, not the money.": "accounts {n} transfers away from a listed account with no recorded outgoing transfers. The data ends here; the money may have moved on.",
  "dead ends the crawl did follow to their end": "accounts with no outgoing transfers that are within the data limit, so the money appears to stay there",
  "of the {n} known clients appear in no transfer at all": "of the {n} listed accounts appear in no transfer",
  "known clients sent nothing in the window": "listed accounts have no outgoing transfers in July",
  "of accounts sit at the crawl boundary": "of accounts are at the 4-transfer limit of the data",
  "of turnover ends at the crawl boundary": "of total KZT ends at the 4-transfer limit of the data",
  "isolated accounts, no transfer either way": "accounts with no transfers in or out",
  "The crawl followed money <b>outwards</b> from the {n} known clients for four hops. Money arriving into them was never followed, so anyone directing them from above is outside this extract by construction. These are the measured limits, and what to ask for next.":
    "The data contains <b>outgoing</b> transfers from the {n} listed accounts, followed for up to 4 transfers onward. Incoming transfers to the listed accounts are not included, so any account that sent money to them is not in the data. The figures below measure these limits.",
  "What to ask the data owner for next": "Additional data to request", "Ranked by what each request would resolve.": "Ordered by the number of accounts each request would cover.",
  "accounts resolved": "accounts covered", "lit up": "of transfers covered", "Not generated in this run.": "Not computed in this run.",
  "Where a plain centrality ranking would mislead": "Accounts whose rank differs most between centrality and the rules",
  "Centrality promotes accounts that flow passes through. It cannot tell an account collecting from many payers apart from a business paying many suppliers. These accounts moved most between the two rankings.":
    "Centrality ranks an account by how much money passes through it. It does not distinguish an account collecting from many payers from a business paying many suppliers. These accounts have the largest difference between the two rankings.",
  "by evidence": "by rules", "the numbers": "figures",
  "A ranking is only worth having if acting on it changes the network.": "How the network changes when the top-ranked accounts are removed.",
  "largest group left": "largest connected group remaining", "separate pieces": "separate groups", "still reachable from known clients": "still reachable from listed accounts",
  "The case in one screen": "Overview",
  "Law enforcement named <b>{n} accounts</b> at the bottom of a chain. A crawl followed their outbound transfers for four hops through July 2026. This tool reads what the crawl brought back and answers one question: <b>which of these accounts should an analyst look at first, and why.</b>":
    "Law enforcement provided a list of <b>{n} accounts</b> (listed accounts). The data contains all outgoing transfers from those accounts for up to 4 transfers onward, 1–31 July 2026. This screen ranks the accounts for review and shows the reason for each rank. <b>Hop: how many transfers away from a listed account.</b>",
  "known clients, where the crawl began": "listed accounts, named by law enforcement", "accounts reached in four hops": "accounts in the data, within 4 transfers",
  "accounts to review first": "priority accounts",
  "structures that only make sense read together": "linked account groups",
  "accounts not judged, because the data does not support a judgement": "accounts not assessed: too few transfers, or at the 4-transfer limit of the data",
  "Start with these accounts": "Highest-priority accounts",
  "Start with these structures": "Highest-priority groups", "All {n} structures": "All {n} groups", "Also in this file": "Also in the data",
  "the busiest day: {kzt} in {n} transfers.": "the day with the most transfers: {kzt} in {n} transfers.",
  "amount echoes: the same sum in and out within a day, or the same sum to several receivers.": "matching amounts: the same sum received and sent within a day, or the same sum sent to several receivers.",
  "See them": "Open the list", "accounts where the crawl stopped rather than the money.": "accounts at the 4-transfer limit of the data with no recorded outgoing transfers.",
  "July 2026, one day at a time, on the same hop layout: known clients on the left, four hops to the right. Watch which days carry the bursts and how far the money travels in a day.":
    "Transfers for each day of July 2026 on the same layout: listed accounts on the left, accounts 1 to 4 transfers away to the right. Shows which days had the most transfers and how far the money moved within a day.",
  "An exact sum arrives at an account and leaves again as the same sum, or split into parts, within a day. Or one account sends the identical amount to several receivers on the same day. Each is a hypothesis for an analyst to check against what the transfers were said to be for.":
    "A sum arrives at an account and the same sum leaves within a day, either whole or split into parts. Or one account sends the same sum to several receivers on the same day. Each case is a hypothesis for the analyst to check against the stated purpose of the transfers.",
};

const RU = {
  "find an account by id": "поиск счёта по ID",
  "Case file": "Выгрузка", "outbound crawl, 4 hops · 1–31 July 2026": "исходящие переводы, до 4 шагов · 1–31 июля 2026",
  "Paper": "Светлая", "Dark": "Тёмная",
  "The run output could not be read. This screen expects out/graph.json beside it, served over HTTP rather than opened from disk. Start it with: python3 run.py --serve":
    "Не удалось прочитать результат расчёта. Файл out/graph.json должен лежать рядом и отдаваться по HTTP, а не открываться с диска. Запуск: python3 run.py --serve",
  "Start": "Обзор", "the case in one screen": "итоги и с чего начать",
  "Who to review first": "Приоритетные счета", "ranked, with reasons": "рейтинг с обоснованием",
  "One account": "Счёт", "its money, its role, its neighbours": "переводы, роль, приоритет",
  "Structures": "Группы счетов", "funnels, chains, loops, fan-outs": "найдены по правилам",
  "Replay the month": "По дням", "July, day by day": "1–31 июля 2026",
  "Amount echoes": "Совпадающие суммы", "same sum in, same sum out": "одна сумма на входе и на выходе за день",
  "Where the data runs out": "Границы данных", "and what to ask for next": "чего нет в выгрузке",
  "Every figure is a measurement from the July extract. Every reading of it is a hypothesis to test, not a finding of guilt.":
    "Все цифры рассчитаны по выгрузке за июль 2026 г. Роли и рейтинг — гипотезы, их проверяет аналитик.",
  "known clients": "счета из списка", "hop {n}": "шаг {n}",
  "2 hops in": "2 шага до", "paid it": "платили ему", "this one": "этот счёт", "paid by it": "получали от него", "2 hops out": "2 шага после",
  "paid the payers": "платили его плательщикам", "paid this account": "платили этому счёту", "this account": "этот счёт",
  "were paid by it": "получали от него", "were paid next": "получали от них",
  "breaking point": "ключевой счёт",
  "An account law enforcement already named": "Счёт из списка правоохранительных органов", "known client": "счёт из списка",
  "All {n} accounts": "Все счета ({n})",
  "left to right is distance from the known clients · the selection and its transfers are lit": "слева направо — шаги от счетов из списка · выбранный счёт и его переводы выделены",
  "Around {id}": "Связи счёта {id}", "paid by {a}, paid {b}": "плательщиков: {a}, получателей: {b}",
  "{n} of them also paid it, drawn once on the left with arrows both ways": "из них в обе стороны: {n}; показаны слева один раз, стрелки в обе стороны",
  "{n} accounts with the smallest transfers are not drawn so the rest stay readable. Whole network shows everything.":
    "Скрыты счета с наименьшими переводами: {n}. В режиме «Все счета» показаны все.",
  "This account": "Этот счёт",
  "Received <b>{in}</b> from {a} and sent <b>{out}</b> to {b} in July.": "За июль получено <b>{in}</b> ({a}), отправлено <b>{out}</b> ({b}).",
  "account": "счёт", "accounts": "счетов",
  "Assessed as": "Роль", "rule confidence": "уверенность правила", "The rule fired on:": "Цифры, по которым сработало правило:",
  "This account sits at hop {n} with nothing recorded going out. The crawl stopped here, so whether the money stopped here is not something this data can say.":
    "Счёт на шаге {n}, исходящих переводов нет. Дальше выгрузка не идёт, поэтому остались ли деньги на счёте — по данным не установить.",
  "Investigation priority": "Приоритет проверки", "of": "из", "not in the top {n}": "вне топ-{n}", "0 to 1, higher first": "шкала 0–1, выше — проверять раньше",
  "Position": "Положение", "hops from a known client": "шагов от счёта из списка", "known": "из списка", "group": "группа",
  "What we know of it": "Полнота данных", "confidence": "уверенность",
  "fully_observed": "есть входящие и исходящие переводы", "outbound_only": "только исходящие переводы", "inbound_only": "только входящие переводы",
  "truncated_at_depth": "на границе выгрузки (4-й шаг)", "isolated": "переводов нет", "partial": "данные частичные",
  "Structures it belongs to": "Входит в группы", "and {n} more": "и ещё {n}",
  "None. It is not part of any funnel, chain, loop, fan-out or bridge.": "Нет. Счёт не входит ни в одну группу.",
  "No account with the id {id} in this extract.": "Счёт {id} в выгрузке не найден.",
  "Pick an account from any list, or type its id above. The map shows the money around it: who paid it on the left, who it paid on the right. Every arrow points the way the money moved.":
    "Выберите счёт в любом списке или введите его ID в поиске. Слева на карте — плательщики счёта, справа — получатели. Стрелки идут от плательщика к получателю.",
  "Around this account": "Связанные счета", "Whole network": "Все счета",
  "A ranked account is a name, and an investigator cannot act on a name. These are groups of accounts that only make sense read together, ranked by what an investigator can act on. Each carries its <b>breaking point</b>: the one account whose removal breaks most of it.":
    "Группы счетов, связанных переводами по правилам. Ранжированы по обороту и по числу участников, зависящих от одного счёта. У каждой группы есть <b>ключевой счёт</b>: без него от группы отсекается больше всего участников.",
  "across": "на", "hop": "шаге", "hops": "шагах", "through it": "оборота внутри группы",
  "{n} more are in out/formations.csv.": "Ещё {n} — в out/formations.csv.",
  "accounts cut off": "отсечено счетов", "KZT stopped": "остановлено KZT",
  "This structure": "Эта группа", "of them known": "из списка", "moving through it": "оборота внутри группы",
  "Breaking point": "Ключевой счёт",
  "Remove this one account and {n} {unit}. Found by {method}. Marked in amber on the map.": "Если убрать этот счёт: {unit} — {n}. Метод: {method}. На карте выделен оранжевым.",
  "Not identified for this structure.": "Для этой группы не определён.",
  "Hypothesis to test": "Гипотеза для проверки", "Arithmetic behind it:": "Расчёт:", "Members": "Участники",
  "The {k} accounts the evidence puts first, out of {n}. Ranked on the rules that fired and the numbers they fired on, not on how central an account is. <b>Click a row</b> to open the account.":
    "Первые {k} из {n} по приоритету. Приоритет считается по сработавшим правилам и их цифрам, а не по числу связей счёта. <b>Нажмите на строку</b>, чтобы открыть счёт.",
  "assessed as": "роль", "priority": "приоритет", "the reason, in the rule's own numbers": "причина: цифры, по которым сработало правило",
  "accounts at hop {n} with nothing going out. The crawl stopped, not the money.": "счетов на шаге {n} без исходящих переводов. Закончилась выгрузка, а не деньги.",
  "dead ends the crawl did follow to their end": "счетов без исходящих переводов внутри границы выгрузки; деньги, по-видимому, остались на них",
  "of the {n} known clients appear in no transfer at all": "из {n} счетов списка нет ни в одном переводе",
  "known clients sent nothing in the window": "счетов из списка без исходящих переводов за июль",
  "of accounts sit at the crawl boundary": "счетов на границе выгрузки (4-й шаг)",
  "of turnover ends at the crawl boundary": "оборота заканчивается на границе выгрузки (4-й шаг)",
  "isolated accounts, no transfer either way": "счетов без переводов: ни входящих, ни исходящих",
  "The crawl followed money <b>outwards</b> from the {n} known clients for four hops. Money arriving into them was never followed, so anyone directing them from above is outside this extract by construction. These are the measured limits, and what to ask for next.":
    "В выгрузке — <b>исходящие</b> переводы счетов из списка ({n}) на глубину до 4 шагов. Входящие переводы на эти счета не выгружались, поэтому их плательщиков в данных нет. Ниже — измеренные границы данных.",
  "What to ask the data owner for next": "Какие данные запросить дополнительно", "Ranked by what each request would resolve.": "По числу счетов, которые покроет запрос.",
  "accounts resolved": "счетов", "lit up": "оборота", "Not generated in this run.": "В этом запуске не рассчитано.",
  "Where a plain centrality ranking would mislead": "Где рейтинг по центральности расходится с правилами",
  "Centrality promotes accounts that flow passes through. It cannot tell an account collecting from many payers apart from a business paying many suppliers. These accounts moved most between the two rankings.":
    "Центральность ранжирует счёт по объёму проходящих через него денег. Она не отличает счёт, собирающий деньги от многих плательщиков, от бизнеса, который платит многим поставщикам. У этих счетов наибольшее расхождение между двумя рейтингами.",
  "by centrality": "по центральности", "by evidence": "по правилам", "the numbers": "цифры",
  "If the top-ranked accounts were removed": "Если убрать верх рейтинга",
  "A ranking is only worth having if acting on it changes the network.": "Как меняется сеть, если убрать счета из верха рейтинга.",
  "removed": "убрано", "largest group left": "крупнейшая оставшаяся группа", "separate pieces": "отдельных групп", "still reachable from known clients": "по-прежнему достижимы от счетов из списка",
  "This section could not start:": "Раздел не запустился:", "This section's module is not present in this build.": "Модуль раздела отсутствует в сборке.",
  "The case in one screen": "Обзор",
  "Law enforcement named <b>{n} accounts</b> at the bottom of a chain. A crawl followed their outbound transfers for four hops through July 2026. This tool reads what the crawl brought back and answers one question: <b>which of these accounts should an analyst look at first, and why.</b>":
    "Правоохранительные органы передали список счетов: <b>{n}</b> (далее — счета из списка). Выгрузка содержит их исходящие переводы на глубину до 4 шагов за 1–31 июля 2026 г. Экран ранжирует счета для проверки и показывает причину каждого места. <b>Шаг — число переводов от счёта из списка.</b>",
  "known clients, where the crawl began": "счетов из списка правоохранительных органов", "accounts reached in four hops": "счетов в выгрузке (до 4 шагов)",
  "transfer relationships": "связей по переводам", "accounts to review first": "приоритетных счетов",
  "structures that only make sense read together": "групп счетов",
  "accounts not judged, because the data does not support a judgement": "счетов без оценки: мало переводов или граница выгрузки",
  "Start with these accounts": "Счета с наибольшим приоритетом", "RANK": "МЕСТО", "PRIORITY": "ПРИОРИТЕТ", "All {n} ranked accounts": "Весь рейтинг ({n})",
  "Start with these structures": "Группы с наибольшим приоритетом", "All {n} structures": "Все группы ({n})", "Also in this file": "Также в выгрузке",
  "the busiest day: {kzt} in {n} transfers.": "самый активный день: {kzt}, переводов: {n}.",
  "amount echoes: the same sum in and out within a day, or the same sum to several receivers.": "совпадающих сумм: одна сумма получена и отправлена за день либо отправлена нескольким получателям.",
  "See them": "Открыть список", "accounts where the crawl stopped rather than the money.": "счетов на границе выгрузки (4-й шаг) без исходящих переводов.",
  "July 2026, one day at a time, on the same hop layout: known clients on the left, four hops to the right. Watch which days carry the bursts and how far the money travels in a day.":
    "Переводы за каждый день июля 2026 г. на той же схеме: счета из списка слева, счета на шагах 1–4 справа. Видно, в какие дни переводов больше всего и как далеко уходят деньги за день.",
  "An exact sum arrives at an account and leaves again as the same sum, or split into parts, within a day. Or one account sends the identical amount to several receivers on the same day. Each is a hypothesis for an analyst to check against what the transfers were said to be for.":
    "Сумма поступает на счёт, и та же сумма уходит в течение дня — целиком или частями. Либо один счёт в один день отправляет одинаковую сумму нескольким получателям. Каждый случай — гипотеза, которую аналитик сверяет с назначением платежа.",
};

const KK = {
  "find an account by id": "шотты ID бойынша іздеу",
  "Case file": "Деректер", "outbound crawl, 4 hops · 1–31 July 2026": "шығыс аударымдар, 4 қадамға дейін · 2026 ж. 1–31 шілде",
  "Paper": "Ашық", "Dark": "Қараңғы",
  "The run output could not be read. This screen expects out/graph.json beside it, served over HTTP rather than opened from disk. Start it with: python3 run.py --serve":
    "Есептеу нәтижесі оқылмады. out/graph.json файлы қасында болып, HTTP арқылы берілуі керек, дискіден ашылмауы керек. Іске қосу: python3 run.py --serve",
  "Start": "Шолу", "the case in one screen": "қорытынды және неден бастау",
  "Who to review first": "Басым шоттар", "ranked, with reasons": "негіздемелі рейтинг",
  "One account": "Шот", "its money, its role, its neighbours": "аударымдар, рөл, басымдық",
  "Structures": "Шот топтары", "funnels, chains, loops, fan-outs": "ережелер бойынша табылған",
  "Replay the month": "Күн бойынша", "July, day by day": "2026 ж. 1–31 шілде",
  "Amount echoes": "Сәйкес сомалар", "same sum in, same sum out": "бір күнде бір сома кіріп, шықты",
  "Where the data runs out": "Деректер шегі", "and what to ask for next": "деректерде не жоқ",
  "Every figure is a measurement from the July extract. Every reading of it is a hypothesis to test, not a finding of guilt.":
    "Барлық сандар 2026 жылғы шілде деректерінен есептелген. Рөлдер мен рейтинг — гипотеза, оны талдаушы тексереді.",
  "known clients": "тізімдегі шоттар", "hop {n}": "{n}-қадам",
  "2 hops in": "2 қадам бұрын", "paid it": "оған төледі", "this one": "осы шот", "paid by it": "одан алды", "2 hops out": "2 қадам кейін",
  "paid the payers": "оның төлеушілеріне төледі", "paid this account": "осы шотқа төледі", "this account": "осы шот",
  "were paid by it": "одан алды", "were paid next": "олардан алды",
  "breaking point": "негізгі шот",
  "An account law enforcement already named": "Құқық қорғау органдары тізіміндегі шот", "known client": "тізімдегі шот",
  "All {n} accounts": "Барлық шот ({n})",
  "left to right is distance from the known clients · the selection and its transfers are lit": "солдан оңға — тізімдегі шоттан қадам саны · таңдалған шот пен оның аударымдары бөлектелген",
  "Around {id}": "{id} шотының байланыстары", "paid by {a}, paid {b}": "төлеуші: {a}, алушы: {b}",
  "{n} of them also paid it, drawn once on the left with arrows both ways": "оның ішінде екі бағытта да: {n}; сол жақта бір рет, екі жақты көрсеткімен көрсетілген",
  "{n} accounts with the smallest transfers are not drawn so the rest stay readable. Whole network shows everything.":
    "Ең кіші аударымды шоттар жасырылған: {n}. «Барлық шоттар» режимінде бәрі көрсетіледі.",
  "This account": "Осы шот",
  "Received <b>{in}</b> from {a} and sent <b>{out}</b> to {b} in July.": "Шілдеде <b>{in}</b> алды ({a}), <b>{out}</b> жіберді ({b}).",
  "account": "шот", "accounts": "шот",
  "Assessed as": "Рөлі", "rule confidence": "ереже сенімділігі", "The rule fired on:": "Ереже сүйенген сандар:",
  "This account sits at hop {n} with nothing recorded going out. The crawl stopped here, so whether the money stopped here is not something this data can say.":
    "Шот {n}-қадамда тұр, шығыс аударымы жоқ. Деректер осында бітеді, сондықтан ақша шотта қалды ма — деректер бойынша анықтау мүмкін емес.",
  "Investigation priority": "Тексеру басымдығы", "of": "/", "not in the top {n}": "топ-{n} ішінде емес", "0 to 1, higher first": "0–1 шкаласы, жоғары болса — ертерек тексеріледі",
  "Position": "Орны", "hops from a known client": "тізімдегі шоттан қадам", "known": "тізімде", "group": "топ",
  "What we know of it": "Деректер толықтығы", "confidence": "сенімділік",
  "fully_observed": "кіріс және шығыс аударымдар бар", "outbound_only": "тек шығыс аударымдар", "inbound_only": "тек кіріс аударымдар",
  "truncated_at_depth": "деректер шегінде (4-қадам)", "isolated": "аударым жоқ", "partial": "деректер ішінара",
  "Structures it belongs to": "Кіретін топтары", "and {n} more": "және тағы {n}",
  "None. It is not part of any funnel, chain, loop, fan-out or bridge.": "Жоқ. Бұл шот ешбір топқа кірмейді.",
  "No account with the id {id} in this extract.": "{id} шоты деректерде табылмады.",
  "Pick an account from any list, or type its id above. The map shows the money around it: who paid it on the left, who it paid on the right. Every arrow points the way the money moved.":
    "Кез келген тізімнен шотты таңдаңыз немесе іздеу жолына ID енгізіңіз. Картада сол жақта — осы шоттың төлеушілері, оң жақта — алушылары. Көрсеткі төлеушіден алушыға бағытталған.",
  "Around this account": "Байланысты шоттар", "Whole network": "Барлық шоттар",
  "A ranked account is a name, and an investigator cannot act on a name. These are groups of accounts that only make sense read together, ranked by what an investigator can act on. Each carries its <b>breaking point</b>: the one account whose removal breaks most of it.":
    "Ережелер бойынша аударымдармен байланысты шот топтары. Айналымы және бір шотқа тәуелді қатысушы саны бойынша ранжирленген. Әр топтың <b>негізгі шоты</b> бар: оны алып тастаса, топтан ең көп қатысушы ажырайды.",
  "across": "·", "hop": "қадам", "hops": "қадам", "through it": "топ ішіндегі айналым",
  "{n} more are in out/formations.csv.": "Тағы {n} — out/formations.csv файлында.",
  "accounts cut off": "шот ажырайды", "KZT stopped": "KZT тоқтайды",
  "This structure": "Осы топ", "of them known": "тізімде", "moving through it": "топ ішіндегі айналым",
  "Breaking point": "Негізгі шот",
  "Remove this one account and {n} {unit}. Found by {method}. Marked in amber on the map.": "Осы шотты алып тастаса, {n} {unit}. Әдіс: {method}. Картада қызғылт сары түспен белгіленген.",
  "Not identified for this structure.": "Бұл топ үшін анықталмаған.",
  "Hypothesis to test": "Тексерілетін гипотеза", "Arithmetic behind it:": "Есебі:", "Members": "Қатысушылар",
  "The {k} accounts the evidence puts first, out of {n}. Ranked on the rules that fired and the numbers they fired on, not on how central an account is. <b>Click a row</b> to open the account.":
    "Басымдығы бойынша алғашқы {k} / {n}. Басымдық шоттың байланыс санымен емес, іске қосылған ережелер мен олардың сандары бойынша есептеледі. Шотты ашу үшін <b>жолды басыңыз</b>.",
  "assessed as": "рөлі", "priority": "басымдық", "the reason, in the rule's own numbers": "себебі: ереже сүйенген сандар",
  "accounts at hop {n} with nothing going out. The crawl stopped, not the money.": "шот {n}-қадамда, шығыс аударымы жоқ. Деректер бітті, ақша емес.",
  "dead ends the crawl did follow to their end": "шот деректер шегінің ішінде, шығыс аударымы жоқ; ақша соларда қалған сияқты",
  "of the {n} known clients appear in no transfer at all": "тізімдегі {n} шоттың ішінен ешбір аударымда жоқ",
  "known clients sent nothing in the window": "тізімдегі шоттың шілдеде шығыс аударымы жоқ",
  "of accounts sit at the crawl boundary": "шот деректер шегінде (4-қадам)",
  "of turnover ends at the crawl boundary": "айналым деректер шегінде бітеді (4-қадам)",
  "isolated accounts, no transfer either way": "шоттың кіріс те, шығыс та аударымы жоқ",
  "The crawl followed money <b>outwards</b> from the {n} known clients for four hops. Money arriving into them was never followed, so anyone directing them from above is outside this extract by construction. These are the measured limits, and what to ask for next.":
    "Деректерде тізімдегі шоттардың ({n}) <b>шығыс</b> аударымдары 4 қадамға дейін қамтылған. Олардың кіріс аударымдары қамтылмаған, сондықтан оларға төлегендер деректерде жоқ. Төменде — деректер шегінің өлшемдері.",
  "What to ask the data owner for next": "Қосымша сұралатын деректер", "Ranked by what each request would resolve.": "Әр сұраныс қамтитын шот саны бойынша реттелген.",
  "accounts resolved": "шот", "lit up": "айналым", "Not generated in this run.": "Бұл жолы есептелмеген.",
  "Where a plain centrality ranking would mislead": "Орталықтық рейтингі ережелерден ең көп алшақтайтын шоттар",
  "Centrality promotes accounts that flow passes through. It cannot tell an account collecting from many payers apart from a business paying many suppliers. These accounts moved most between the two rankings.":
    "Орталықтық шотты ол арқылы өткен ақша көлемі бойынша ранжирлейді. Ол көп төлеушіден ақша жинайтын шотты көп жеткізушіге төлейтін бизнестен ажырата алмайды. Бұл шоттарда екі рейтингтің айырмасы ең үлкен.",
  "by centrality": "орталықтық", "by evidence": "ережелер", "the numbers": "сандар",
  "If the top-ranked accounts were removed": "Рейтингтің басындағы шоттарды алып тастаса",
  "A ranking is only worth having if acting on it changes the network.": "Рейтингтің басындағы шоттарды алып тастағанда желі қалай өзгереді.",
  "removed": "алынды", "largest group left": "қалған ең үлкен топ", "separate pieces": "бөлек топ", "still reachable from known clients": "тізімдегі шоттардан әлі қолжетімді",
  "This section could not start:": "Бөлім іске қосылмады:", "This section's module is not present in this build.": "Бұл бөлімнің модулі жинақта жоқ.",
  "The case in one screen": "Шолу",
  "Law enforcement named <b>{n} accounts</b> at the bottom of a chain. A crawl followed their outbound transfers for four hops through July 2026. This tool reads what the crawl brought back and answers one question: <b>which of these accounts should an analyst look at first, and why.</b>":
    "Құқық қорғау органдары шоттар тізімін берді: <b>{n}</b> (бұдан әрі — тізімдегі шоттар). Деректерде олардың 2026 жылғы 1–31 шілдедегі шығыс аударымдары 4 қадамға дейін қамтылған. Экран шоттарды тексеруге ранжирлейді және әр орынның себебін көрсетеді. <b>Қадам — тізімдегі шоттан аударым саны.</b>",
  "known clients, where the crawl began": "құқық қорғау органдары тізіміндегі шот", "accounts reached in four hops": "деректердегі шот (4 қадамға дейін)",
  "transfer relationships": "аударым байланысы", "accounts to review first": "басым шот",
  "structures that only make sense read together": "шот тобы",
  "accounts not judged, because the data does not support a judgement": "бағаланбаған шот: аударым аз немесе деректер шегі",
  "Start with these accounts": "Басымдығы ең жоғары шоттар", "RANK": "ОРЫН", "PRIORITY": "БАСЫМДЫҚ", "All {n} ranked accounts": "Толық рейтинг ({n})",
  "Start with these structures": "Басымдығы ең жоғары топтар", "All {n} structures": "Барлық топ ({n})", "Also in this file": "Деректерде тағы",
  "the busiest day: {kzt} in {n} transfers.": "ең белсенді күн: {kzt}, аударым саны: {n}.",
  "amount echoes: the same sum in and out within a day, or the same sum to several receivers.": "сәйкес сома: бір сома бір күнде алынып, жіберілген немесе бірнеше алушыға жіберілген.",
  "See them": "Тізімді ашу", "accounts where the crawl stopped rather than the money.": "шот деректер шегінде (4-қадам), шығыс аударымы жоқ.",
  "July 2026, one day at a time, on the same hop layout: known clients on the left, four hops to the right. Watch which days carry the bursts and how far the money travels in a day.":
    "2026 жылғы шілденің әр күнінің аударымдары сол сызбада: тізімдегі шоттар сол жақта, 1–4 қадамдағы шоттар оң жақта. Қай күні аударым көп болғаны және ақшаның бір күнде қанша қадам өткені көрінеді.",
  "An exact sum arrives at an account and leaves again as the same sum, or split into parts, within a day. Or one account sends the identical amount to several receivers on the same day. Each is a hypothesis for an analyst to check against what the transfers were said to be for.":
    "Сома шотқа түседі, сол сома бір күн ішінде тұтас немесе бөлшектеп шығады. Немесе бір шот бір күнде бірдей соманы бірнеше алушыға жібереді. Әр жағдай — гипотеза; талдаушы оны төлем мақсатымен салыстырып тексереді.",
};

const DICT = { ru: RU, kk: KK, en: EN };
export const t = k => DICT[LANG][k] ?? k;

/* Role names and their plain definitions. The thresholds are the ones in src/moneygraph/roles.py. */
const ROLE_NAMES = {
  ru: { consolidator: "консолидатор", coordinator: "координатор", transit: "транзит", distributor: "распределитель", terminal: "конечный получатель",
        peripheral: "низкая активность", abstained_boundary: "без оценки: граница данных", abstained_single_observation: "без оценки: мало переводов", "known client": "счёт из списка" },
  kk: { consolidator: "консолидатор", coordinator: "координатор", transit: "транзит", distributor: "таратушы", terminal: "соңғы алушы",
        peripheral: "белсенділігі төмен", abstained_boundary: "бағаланбаған: деректер шегі", abstained_single_observation: "бағаланбаған: аударым аз", "known client": "тізімдегі шот" },
  en: { terminal: "final recipient", peripheral: "low activity", abstained_boundary: "not assessed: data limit", abstained_single_observation: "not assessed: too few transfers", "known client": "listed account" },
};
const ROLE_DEFS = {
  en: {
    consolidator: "Receives from 8 or more different accounts and sends on less than half of what it receives.",
    coordinator: "Receives from 4 or more accounts and sends to 4 or more accounts.",
    transit: "Sends on between 80% and 120% of what it receives.",
    distributor: "Sends to 20 or more different accounts.",
    terminal: "Receives money and sends none on, and is fewer than 4 transfers away from a listed account, so the money appears to stay here.",
    peripheral: "No rule threshold met: few transfers, or a listed account with only outgoing transfers recorded.",
    abstained_boundary: "4 transfers away from a listed account with no outgoing transfers. The data ends here, so no role is assigned.",
    abstained_single_observation: "Fewer than 3 transfers in total. Too few to assign a role.",
  },
  ru: {
    consolidator: "Получает от 8 и более счетов, дальше отправляет меньше половины полученного.",
    coordinator: "Получает от 4 и более счетов и отправляет на 4 и более счетов.",
    transit: "Отправляет дальше от 80 до 120 % полученного.",
    distributor: "Отправляет на 20 и более счетов.",
    terminal: "Получает и дальше ничего не отправляет; находится ближе 4 шагов от счёта из списка, поэтому деньги, по-видимому, остаются здесь.",
    peripheral: "Ни один порог не достигнут: мало переводов, либо счёт из списка, у которого выгружены только исходящие переводы.",
    abstained_boundary: "На 4-м шаге от счёта из списка, исходящих переводов нет. Выгрузка здесь заканчивается, роль не присваивается.",
    abstained_single_observation: "Меньше 3 переводов всего. Для присвоения роли мало.",
  },
  kk: {
    consolidator: "8 және одан көп шоттан алады, алғанының жартысынан азын әрі қарай жібереді.",
    coordinator: "4 және одан көп шоттан алады және 4 және одан көп шотқа жібереді.",
    transit: "Алғанының 80–120 %-ын әрі қарай жібереді.",
    distributor: "20 және одан көп шотқа жібереді.",
    terminal: "Ақша алады, әрі қарай жібермейді; тізімдегі шоттан 4 қадамнан жақын тұр, сондықтан ақша осында қалған сияқты.",
    peripheral: "Ешбір шекке жетпеген: аударым аз немесе тек шығыс аударымы бар тізімдегі шот.",
    abstained_boundary: "Тізімдегі шоттан 4-қадамда тұр, шығыс аударымы жоқ. Деректер осында бітеді, рөл берілмейді.",
    abstained_single_observation: "Барлығы 3-тен аз аударым. Рөл беруге аз.",
  },
};
const KIND_NAMES = {
  ru: { funnel: "точка сбора", chain: "цепочка переводов", reciprocal_loop: "возврат средств", fan_out: "один отправитель — много получателей", bridge: "единственная связь с сетью" },
  kk: { funnel: "жинау нүктесі", chain: "аударым тізбегі", reciprocal_loop: "қаражат қайтарымы", fan_out: "бір жіберуші — көп алушы", bridge: "желімен жалғыз байланыс" },
  en: { funnel: "collection point", chain: "forwarding chain", reciprocal_loop: "money returned", fan_out: "one sender, many receivers", bridge: "single link to the network" },
};
const KIND_DEFS = {
  en: {
    funnel: "several accounts each send most of their outgoing money to the same account",
    chain: "money is forwarded from account to account, each sending on most of what it received",
    reciprocal_loop: "money is sent and then sent back, between two accounts or around a short cycle",
    fan_out: "one account sends to many accounts that send nothing on",
    bridge: "one account through which part of the group is connected to the rest of the network",
  },
  ru: {
    funnel: "несколько счетов отправляют большую часть исходящих переводов на один и тот же счёт",
    chain: "деньги идут от счёта к счёту, каждый передаёт дальше большую часть полученного",
    reciprocal_loop: "деньги отправлены и возвращены: между двумя счетами или по короткому кругу",
    fan_out: "один счёт отправляет многим счетам, которые дальше ничего не отправляют",
    bridge: "один счёт, через который часть группы связана с остальной сетью",
  },
  kk: {
    funnel: "бірнеше шот шығыс аударымының көп бөлігін бір шотқа жібереді",
    chain: "ақша шоттан шотқа өтеді, әр шот алғанының көп бөлігін әрі қарай жібереді",
    reciprocal_loop: "ақша жіберіліп, қайтарылады: екі шот арасында немесе қысқа айналыммен",
    fan_out: "бір шот көп шотқа жібереді, олар әрі қарай ештеңе жібермейді",
    bridge: "топтың бір бөлігін желінің қалған бөлігімен жалғайтын жалғыз шот",
  },
};
export const ROLE_DEF = ROLE_DEFS[LANG];
export const KIND_DEF = KIND_DEFS[LANG];
export const roleName = r => ROLE_NAMES[LANG][r] ?? String(r ?? "").replace(/_/g, " ");
export const kindName = k => KIND_NAMES[LANG][k] ?? String(k ?? "").replace(/_/g, " ");
